### ISSUE TITLE
"HTML5 and ARIA" tab hover inconsistent

### ISSUE THREAD

**Issue by rheveleigh** [vga-/wave-auto-a11y#20]
For Detailed Reports, multiple URLs:
Mouse hover behavior (highlight) not consistent on each occurrence of "HTML5 and ARIA" tab.

**Comment by vabruzzo** [comment]
I'm not sure what you mean, can you give a little more detail

**Comment by vabruzzo** [comment]
> I ran a Detailed Report of 3 Web sites.
> 
> The results of the 3 scans were presented at the bottom of the page.
> 
> When I hovered the mouse over any of the 7 tabs (Errors, Alerts, etc), each individual tab responded/modified (highlight & outline visually).  However, for only some of the Detailed Reports on the page, the “HTML5 and ARIA” tab did not “modify” (highlight? enlarge? outline?) when I hovered the mouse over the tab.  All other tabs did “modify” when mouse-hovered.  Behavior observed in both Chrome and Firefox.
> 
> Make sense?

Yeah that make's sense. Was the result for the category 0? If there are 0 items, then there is no tab content and the tab is inactive. Can you give me the list of URLs that you scanned so I can test myself.

**Comment by rheveleigh** [comment]
Ah, that may be it. Oops. I'll confirm next time I'm on a non-phone device.

**Comment by rheveleigh** [comment]
Indeed, the HTML5 and ARIA results were “0” for the non-hover-highlighting tabs.  However, I see that the HTML file export omits the “zero” result (omits a HTML5 and ARIA line item).  WAVE Extension results do include lines for “zero” result categories.  I think it would be good to include in the export files all category line items, including those with “zero” results.

**Comment by rheveleigh** [comment]
New thought.  We discussed adding the Summary results (that include categories with zero results) to the Detailed Reports.  So, as long as zero-result categories are included somewhere (as a top summary?) in the Detailed Reports, it seems it may be fine to omit lines for zero-result categories from the "detailed" section of the Detailed Reports.  Thoughts?

**Comment by vabruzzo** [comment]
Yeah I think that's the way to go. So when I implement #18 this will be fixed as well.
